# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', error_messages={'null': 'Game Title is required'}, max_length=250, verbose_name='Game title')),
                ('platform', models.CharField(error_messages={'null': 'Game Platform is required'}, max_length=100)),
                ('score', models.FloatField(default=0.0, max_length=10)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('editors_choice', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
